language: swift
osx_image: xcode10.1

xcode_workspace: CotEditor.xcworkspace
xcode_scheme: CotEditor
xcode_destination: platform=macOS
xcodebuild_args: CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS="" ENABLE_HARDENED_RUNTIME=NO
